name: Build project
on:
  push:
    branches:
      - main
      - development
jobs:
  buildWebGL:
    name: Build for WebGL
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
        key: Library-build-WebGL
        restore-keys: |
          Library-build-
          Library-
   
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
      - uses: actions/upload-artifacts@v3
        with:
          name: build-WebGL
        path: build-WebGL
 
deployPages:
  needs: buildWebGL
  name: Deploy to Itch.io
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
      with:
        name: build-WebGL
      path: build
    - name: Display structure of root files
    - run: ls -R
      working-directory: build/WebGL
    - uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: itch-io
      folder: build/WebGL
    - uses: manleydev/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
        CHANNEL: HTML
        ITCH_GAME: test-cicd
        ITCH_USER: wanottah
        BRANCH: itch-io
        PACKAGE: build/WebGL
